# Generated by Django 4.2.4 on 2024-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_contentlistmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='uuid',
            field=models.UUIDField(default=0, editable=False),
        ),
    ]
