# Generated by Django 4.2.4 on 2023-11-03 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0005_remove_contentlistmodel_posts_postmodel_content_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='messages',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disslikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='files',
            field=models.ManyToManyField(blank=True, to='posts_app.filemodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
