# Generated by Django 4.2.4 on 2024-01-06 19:28

from django.db import migrations, models
import imagekit.models.fields
import posts_app.custom


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0013_remove_contentlistmodel_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='files',
            field=models.FileField(storage=posts_app.custom.FirebaseStorage(), upload_to='files'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, storage=posts_app.custom.FirebaseStorage(), upload_to='images/gallery'),
        ),
    ]
