# Generated by Django 4.2.4 on 2024-01-05 23:21

from django.db import migrations
import posts_app.custom
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0013_remove_contentlistmodel_posts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                storage=posts_app.custom.FirebaseStorage(),
                upload_to="gallery",
                variations={"thumbnail": (100, 100, True)},
            ),
        ),
    ]
