# Generated by Django 4.2.4 on 2024-01-06 09:46

from django.db import migrations
import imagekit.models.fields
import posts_app.custom


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0014_alter_postmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                storage=posts_app.custom.FirebaseStorage(),
                upload_to="gallery",
            ),
        ),
    ]
