# Generated by Django 4.2.4 on 2024-01-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0016_postmodel_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmodel",
            name="user_photo",
        ),
    ]
