# Generated by Django 4.2.4 on 2023-10-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0002_newspapermodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspapermodel',
            old_name='img',
            new_name='image',
        ),
    ]
