# Generated by Django 4.2.4 on 2023-09-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0002_alter_messagesmodel_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagesmodel",
            name="title",
        ),
    ]
