# Generated by Django 4.2.3 on 2023-07-29 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_denunciations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='denunciations',
            field=models.ManyToManyField(blank=True, help_text='Complaints imposed by other users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
