# Generated by Django 4.2.4 on 2024-09-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
