# Generated by Django 4.2.4 on 2023-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0010_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Descripcion del usuario",
                max_length=1000,
                null=True,
            ),
        ),
    ]
