# Generated by Django 4.2.4 on 2023-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0011_alter_user_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isProfessor",
            field=models.BooleanField(default=False),
        ),
    ]
