# Generated by Django 4.2.4 on 2024-01-09 16:16

import api.customs.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Límite de texto excedido'}, help_text='Titulo de la noticia', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, storage=api.customs.custom_storage.FirebaseStorage(), upload_to='images/news')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
