# Generated by Django 4.2.4 on 2023-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Límite de texto excedido'}, help_text='Titulo de la noticia', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
        ),
    ]
