# Generated by Django 4.2.4 on 2023-10-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
