# Generated by Django 4.2.4 on 2023-10-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newsmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(error_messages={'max_length': 'Límite de texto excedido'}, help_text='Titulo de la noticia', max_length=100),
        ),
    ]
